default[:moodle][:site_dir] = '/var/www/moodle'
default[:moodle][:data_dir] = '/var/lib/moodledata'
default[:moodle][:user] = 'www-data'
default[:moodle][:group] = 'www-data'
default[:moodle][:branch] = 'MOODLE_25_STABLE'
